version: "3.9"

services:
  nim:
    build: 
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ../:/workspace:cached
    environment:
      SHELL: /bin/bash